import { TYPE_CHANGE_BACKGROUND_SQUARE_PROPS, TYPE_ADD_BACKGROUND_SQUARE_PROPS } from "../../types/redux/action-types";

export const CHANGE_BACKGROUND_SQUARE_PROPS: TYPE_CHANGE_BACKGROUND_SQUARE_PROPS = "CHANGE_BACKGROUND_SQUARE_PROPS";
export const ADD_BACKGROUND_SQUARE_PROPS: TYPE_ADD_BACKGROUND_SQUARE_PROPS = "ADD_BACKGROUND_SQUARE_PROPS";
