import {CHANGE_BACKGROUND_SQUARE_PROPS,
    ADD_BACKGROUND_SQUARE_PROPS,
    CHANGE_ABOUT_ME_PROPS,
    CHANGE_CREATED_PROPS,
    CHANGE_TOOLS_PROPS,
    CHANGE_CONTACT_PROPS,
    CHANGE_BLOG_PROPS,
    CHANGE_ABOUT_ME_CONTENT_PROPS,
    CHANGE_CREATED_CONTENT_PROPS,
    CHANGE_TOOLS_CONTENT_PROPS,
    CHANGE_CONTACT_CONTENT_PROPS,
    CHANGE_BLOG_CONTENT_PROPS
} from '../../redux/constant/action-types'

export type TYPE_CHANGE_BACKGROUND_SQUARE_PROPS = CHANGE_BACKGROUND_SQUARE_PROPS;
export type TYPE_ADD_BACKGROUND_SQUARE_PROPS = ADD_BACKGROUND_SQUARE_PROPS;

export type TYPE_CHANGE_ABOUT_ME_PROPS = CHANGE_ABOUT_ME_PROPS;
export type TYPE_CHANGE_CREATED_PROPS = CHAGNE_CREATED_PROPS;
export type TYPE_CHANGE_TOOLS_PROPS = CHANGE_TOOLS_PROPS;
export type TYPE_CHANGE_CONTACT_PROPS = CHANGE_CONTACT_PROPS;
export type TYPE_CHANGE_BLOG_PROPS = CHANGE_BLOG_PROPS;

export type TYPE_CHANGE_ABOUT_ME_CONTENT_PROPS = CHANGE_ABOUT_ME_CONTENT_PROPS;
export type TYPE_CHANGE_CREATED_CONTENT_PROPS = CHANGE_CREATED_CONTENT_PROPS;
export type TYPE_CHANGE_TOOLS_CONTENT_PROPS = CHANGE_TOOLS_CONTENT_PROPS;
export type TYPE_CHANGE_CONTACT_CONTENT_PROPS = CHANGE_CONTACT_CONTENT_PROPS;
export type TYPE_CHANGE_BLOG_CONTENT_PROPS = CHANGE_BLOG_CONTENT_PROPS;
