import { CHANGE_BACKGROUND_SQUARE_PROPS, ADD_BACKGROUND_SQUARE_PROPS, CHANGE_ABOUT_ME_PROPS } from '../../redux/constant/action-types'

export type TYPE_CHANGE_BACKGROUND_SQUARE_PROPS = CHANGE_BACKGROUND_SQUARE_PROPS;
export type TYPE_ADD_BACKGROUND_SQUARE_PROPS = ADD_BACKGROUND_SQUARE_PROPS;

export type TYPE_CHANGE_ABOUT_ME_PROPS = CHANGE_ABOUT_ME_PROPS;
